# Generated by Django 5.0.1 on 2024-01-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
