# Generated by Django 5.0.1 on 2024-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='image',
            field=models.ImageField(upload_to='getUploadPath'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='image',
            field=models.ImageField(upload_to='getUploadPath'),
        ),
    ]
