# Generated by Django 5.0.1 on 2024-01-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_historymodel_image_alter_requestmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='image',
            field=models.ImageField(upload_to='history/'),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='image',
            field=models.ImageField(upload_to='request/'),
        ),
    ]
