# Generated by Django 5.0.1 on 2024-01-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_historymodel_image_alter_historymodel_issaved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='fileName',
        ),
    ]
