# Generated by Django 5.0.1 on 2024-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_requestmodel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='similarities',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
